import type { MergedTrip, ScheduleReportRow } from "./types";

const sampleTrips = (scheduleCode: string, shift: "Morning" | "Evening"): MergedTrip[] => [
  {
    companyId: "t",
    siteId: "khapri",
    schedulingDate: new Date().toISOString().slice(0, 10),
    scheduleCode,
    shift,
    vehicleType: "Electric",
    busType: "12m",
    vehicleNumber: "MH-12-AB-1107",
    startTime: "06:00",
    endTime: "06:45",
    fromStage: "Depot",
    toStage: "A",
    distanceInKM: 8.2,
    aDistanceInKM: 8.2,
    employeeCode: "DRV-101",
    driverName: "Rajesh Kumar",
    isLost: 0,
    isShort: 0,
    remark: 0,
    reason: "",
    tripNumber: 1,
    isScheduleCodeChanged: 0,
    tripKey: `${scheduleCode}::1`,
    hasOverride: false,
    status: "completed",
    route: scheduleCode.split("-").slice(0, 2).join("-"),
    zone: "North",
    runningBoard: scheduleCode,
  },
  {
    companyId: "t",
    siteId: "khapri",
    schedulingDate: new Date().toISOString().slice(0, 10),
    scheduleCode,
    shift,
    vehicleType: "Electric",
    busType: "12m",
    vehicleNumber: "MH-12-AB-1107",
    startTime: "07:00",
    endTime: "07:30",
    fromStage: "A",
    toStage: "B",
    distanceInKM: 10.1,
    aDistanceInKM: 10.1,
    employeeCode: "DRV-101",
    driverName: "Rajesh Kumar",
    isLost: 1,
    isShort: 0,
    remark: 2,
    reason: "Driver delay at stage",
    tripNumber: 2,
    isScheduleCodeChanged: 0,
    tripKey: `${scheduleCode}::2`,
    hasOverride: true,
    status: "lost",
    route: scheduleCode.split("-").slice(0, 2).join("-"),
    zone: "North",
    runningBoard: scheduleCode,
  },
  {
    companyId: "t",
    siteId: "khapri",
    schedulingDate: new Date().toISOString().slice(0, 10),
    scheduleCode,
    shift,
    vehicleType: "Electric",
    busType: "12m",
    vehicleNumber: "MH-12-AB-1107",
    startTime: "08:00",
    endTime: "08:40",
    fromStage: "B",
    toStage: "Closing",
    distanceInKM: 9.5,
    aDistanceInKM: 9.5,
    employeeCode: "DRV-101",
    driverName: "Rajesh Kumar",
    isLost: 0,
    isShort: 1,
    remark: 0,
    reason: "Ended early",
    tripNumber: 3,
    isScheduleCodeChanged: 0,
    tripKey: `${scheduleCode}::3`,
    hasOverride: false,
    status: "short",
    route: scheduleCode.split("-").slice(0, 2).join("-"),
    zone: "North",
    runningBoard: scheduleCode,
  },
  {
    companyId: "t",
    siteId: "khapri",
    schedulingDate: new Date().toISOString().slice(0, 10),
    scheduleCode,
    shift,
    vehicleType: "Electric",
    busType: "12m",
    vehicleNumber: "MH-12-AB-1107",
    startTime: "09:00",
    endTime: "09:20",
    fromStage: "Depot",
    toStage: "A",
    distanceInKM: 5.5,
    aDistanceInKM: 5.5,
    employeeCode: "DRV-101",
    driverName: "Rajesh Kumar",
    isLost: 0,
    isShort: 0,
    remark: 0,
    reason: "Extra run approved",
    tripNumber: 9001,
    isScheduleCodeChanged: 0,
    tripKey: `${scheduleCode}::9001`,
    hasOverride: true,
    status: "extra",
    route: scheduleCode.split("-").slice(0, 2).join("-"),
    zone: "North",
    runningBoard: scheduleCode,
  },
];

/** Representative schedule rows for template editor live preview */
export function sampleScheduleReports(siteName: string): ScheduleReportRow[] {
  const base = {
    schedulingDate: new Date().toISOString().slice(0, 10),
    zone: siteName,
    service: "Regular",
    depotStartKm: 4.2,
    aToBKm: 18.5,
    bToAKm: 17.8,
    closingDepotKm: 4.1,
    roundTripKm: 44.6,
    scheduleStartTime: "06:00",
    scheduleEndTime: "14:30",
    hasAdjustment: false,
  };

  return [
    {
      key: "preview-1",
      scheduleCode: "RT-101-AM",
      shift: "Morning",
      driverId: "DRV-101",
      driverName: "Rajesh Kumar",
      runningBoard: "RB-101",
      busNo: "MH-12-AB-1107",
      busType: "12m Low Floor",
      vehicleType: "Electric",
      route: "RT-101",
      ...base,
      metrics: {
        scheduledTrips: 4,
        tripCompleted: 2,
        tripNotCompleted: 1,
        shortTrip: 1,
        lossA1: 0,
        lossA2: 1,
        lossB: 0,
        lossC: 0,
        lossE1: 0,
        lossE2: 0,
        totalLoss: 1,
        completedKMs: 42.3,
        lossKMs: 10.1,
        extraKMs: 5.5,
        billingKMs: 47.8,
        extraTripCount: 1,
      },
      trips: sampleTrips("RT-101-AM", "Morning"),
    },
    {
      key: "preview-2",
      scheduleCode: "RT-205-PM",
      shift: "Evening",
      driverId: "DRV-204",
      driverName: "Suresh Patil",
      runningBoard: "RB-205",
      busNo: "MH-12-CD-1203",
      busType: "9m Midi",
      vehicleType: "Electric",
      route: "RT-205",
      ...base,
      hasAdjustment: true,
      metrics: {
        scheduledTrips: 3,
        tripCompleted: 3,
        tripNotCompleted: 0,
        shortTrip: 0,
        lossA1: 0,
        lossA2: 0,
        lossB: 0,
        lossC: 0,
        lossE1: 0,
        lossE2: 0,
        totalLoss: 0,
        completedKMs: 38.1,
        lossKMs: 0,
        extraKMs: 0,
        billingKMs: 38.1,
        extraTripCount: 0,
      },
      trips: sampleTrips("RT-205-PM", "Evening").slice(0, 2),
    },
  ];
}

/** Flatten sample trips for pivot preview */
export function sampleMergedTrips(siteName: string): MergedTrip[] {
  return sampleScheduleReports(siteName).flatMap((r) => r.trips);
}
