/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as MisRouteImport } from './routes/mis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LauncherRouteImport } from './routes/launcher'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DataSyncRouteImport } from './routes/data-sync'
import { Route as ChargingRouteImport } from './routes/charging'
import { Route as BatteryCyclesRouteImport } from './routes/battery-cycles'
import { Route as AttributeScoreRouteImport } from './routes/attribute-score'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadinessIndexRouteImport } from './routes/readiness.index'
import { Route as ReadinessOpsRouteImport } from './routes/readiness.ops'
import { Route as ReadinessConfigRouteImport } from './routes/readiness.config'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const MisRoute = MisRouteImport.update({
  id: '/mis',
  path: '/mis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherRoute = LauncherRouteImport.update({
  id: '/launcher',
  path: '/launcher',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSyncRoute = DataSyncRouteImport.update({
  id: '/data-sync',
  path: '/data-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargingRoute = ChargingRouteImport.update({
  id: '/charging',
  path: '/charging',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteryCyclesRoute = BatteryCyclesRouteImport.update({
  id: '/battery-cycles',
  path: '/battery-cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributeScoreRoute = AttributeScoreRouteImport.update({
  id: '/attribute-score',
  path: '/attribute-score',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessIndexRoute = ReadinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadinessRoute,
} as any)
const ReadinessOpsRoute = ReadinessOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => ReadinessRoute,
} as any)
const ReadinessConfigRoute = ReadinessConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ReadinessRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attribute-score': typeof AttributeScoreRoute
  '/battery-cycles': typeof BatteryCyclesRoute
  '/charging': typeof ChargingRoute
  '/data-sync': typeof DataSyncRoute
  '/drivers': typeof DriversRoute
  '/esg': typeof EsgRoute
  '/fleet': typeof FleetRoute
  '/intelligence': typeof IntelligenceRoute
  '/launcher': typeof LauncherRoute
  '/login': typeof LoginRoute
  '/mis': typeof MisRoute
  '/readiness': typeof ReadinessRouteWithChildren
  '/routes': typeof RoutesRoute
  '/segments': typeof SegmentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/readiness/config': typeof ReadinessConfigRoute
  '/readiness/ops': typeof ReadinessOpsRoute
  '/readiness/': typeof ReadinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attribute-score': typeof AttributeScoreRoute
  '/battery-cycles': typeof BatteryCyclesRoute
  '/charging': typeof ChargingRoute
  '/data-sync': typeof DataSyncRoute
  '/drivers': typeof DriversRoute
  '/esg': typeof EsgRoute
  '/fleet': typeof FleetRoute
  '/intelligence': typeof IntelligenceRoute
  '/launcher': typeof LauncherRoute
  '/login': typeof LoginRoute
  '/mis': typeof MisRoute
  '/routes': typeof RoutesRoute
  '/segments': typeof SegmentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/readiness/config': typeof ReadinessConfigRoute
  '/readiness/ops': typeof ReadinessOpsRoute
  '/readiness': typeof ReadinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attribute-score': typeof AttributeScoreRoute
  '/battery-cycles': typeof BatteryCyclesRoute
  '/charging': typeof ChargingRoute
  '/data-sync': typeof DataSyncRoute
  '/drivers': typeof DriversRoute
  '/esg': typeof EsgRoute
  '/fleet': typeof FleetRoute
  '/intelligence': typeof IntelligenceRoute
  '/launcher': typeof LauncherRoute
  '/login': typeof LoginRoute
  '/mis': typeof MisRoute
  '/readiness': typeof ReadinessRouteWithChildren
  '/routes': typeof RoutesRoute
  '/segments': typeof SegmentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/readiness/config': typeof ReadinessConfigRoute
  '/readiness/ops': typeof ReadinessOpsRoute
  '/readiness/': typeof ReadinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attribute-score'
    | '/battery-cycles'
    | '/charging'
    | '/data-sync'
    | '/drivers'
    | '/esg'
    | '/fleet'
    | '/intelligence'
    | '/launcher'
    | '/login'
    | '/mis'
    | '/readiness'
    | '/routes'
    | '/segments'
    | '/auth/callback'
    | '/readiness/config'
    | '/readiness/ops'
    | '/readiness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attribute-score'
    | '/battery-cycles'
    | '/charging'
    | '/data-sync'
    | '/drivers'
    | '/esg'
    | '/fleet'
    | '/intelligence'
    | '/launcher'
    | '/login'
    | '/mis'
    | '/routes'
    | '/segments'
    | '/auth/callback'
    | '/readiness/config'
    | '/readiness/ops'
    | '/readiness'
  id:
    | '__root__'
    | '/'
    | '/attribute-score'
    | '/battery-cycles'
    | '/charging'
    | '/data-sync'
    | '/drivers'
    | '/esg'
    | '/fleet'
    | '/intelligence'
    | '/launcher'
    | '/login'
    | '/mis'
    | '/readiness'
    | '/routes'
    | '/segments'
    | '/auth/callback'
    | '/readiness/config'
    | '/readiness/ops'
    | '/readiness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributeScoreRoute: typeof AttributeScoreRoute
  BatteryCyclesRoute: typeof BatteryCyclesRoute
  ChargingRoute: typeof ChargingRoute
  DataSyncRoute: typeof DataSyncRoute
  DriversRoute: typeof DriversRoute
  EsgRoute: typeof EsgRoute
  FleetRoute: typeof FleetRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LauncherRoute: typeof LauncherRoute
  LoginRoute: typeof LoginRoute
  MisRoute: typeof MisRoute
  ReadinessRoute: typeof ReadinessRouteWithChildren
  RoutesRoute: typeof RoutesRoute
  SegmentsRoute: typeof SegmentsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis': {
      id: '/mis'
      path: '/mis'
      fullPath: '/mis'
      preLoaderRoute: typeof MisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher': {
      id: '/launcher'
      path: '/launcher'
      fullPath: '/launcher'
      preLoaderRoute: typeof LauncherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sync': {
      id: '/data-sync'
      path: '/data-sync'
      fullPath: '/data-sync'
      preLoaderRoute: typeof DataSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charging': {
      id: '/charging'
      path: '/charging'
      fullPath: '/charging'
      preLoaderRoute: typeof ChargingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battery-cycles': {
      id: '/battery-cycles'
      path: '/battery-cycles'
      fullPath: '/battery-cycles'
      preLoaderRoute: typeof BatteryCyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attribute-score': {
      id: '/attribute-score'
      path: '/attribute-score'
      fullPath: '/attribute-score'
      preLoaderRoute: typeof AttributeScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/': {
      id: '/readiness/'
      path: '/'
      fullPath: '/readiness/'
      preLoaderRoute: typeof ReadinessIndexRouteImport
      parentRoute: typeof ReadinessRoute
    }
    '/readiness/ops': {
      id: '/readiness/ops'
      path: '/ops'
      fullPath: '/readiness/ops'
      preLoaderRoute: typeof ReadinessOpsRouteImport
      parentRoute: typeof ReadinessRoute
    }
    '/readiness/config': {
      id: '/readiness/config'
      path: '/config'
      fullPath: '/readiness/config'
      preLoaderRoute: typeof ReadinessConfigRouteImport
      parentRoute: typeof ReadinessRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReadinessRouteChildren {
  ReadinessConfigRoute: typeof ReadinessConfigRoute
  ReadinessOpsRoute: typeof ReadinessOpsRoute
  ReadinessIndexRoute: typeof ReadinessIndexRoute
}

const ReadinessRouteChildren: ReadinessRouteChildren = {
  ReadinessConfigRoute: ReadinessConfigRoute,
  ReadinessOpsRoute: ReadinessOpsRoute,
  ReadinessIndexRoute: ReadinessIndexRoute,
}

const ReadinessRouteWithChildren = ReadinessRoute._addFileChildren(
  ReadinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributeScoreRoute: AttributeScoreRoute,
  BatteryCyclesRoute: BatteryCyclesRoute,
  ChargingRoute: ChargingRoute,
  DataSyncRoute: DataSyncRoute,
  DriversRoute: DriversRoute,
  EsgRoute: EsgRoute,
  FleetRoute: FleetRoute,
  IntelligenceRoute: IntelligenceRoute,
  LauncherRoute: LauncherRoute,
  LoginRoute: LoginRoute,
  MisRoute: MisRoute,
  ReadinessRoute: ReadinessRouteWithChildren,
  RoutesRoute: RoutesRoute,
  SegmentsRoute: SegmentsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
