/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as MisRouteImport } from './routes/mis'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ChargingRouteImport } from './routes/charging'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadinessIndexRouteImport } from './routes/readiness.index'
import { Route as ReadinessOpsRouteImport } from './routes/readiness.ops'
import { Route as ReadinessConfigRouteImport } from './routes/readiness.config'

const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const MisRoute = MisRouteImport.update({
  id: '/mis',
  path: '/mis',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargingRoute = ChargingRouteImport.update({
  id: '/charging',
  path: '/charging',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessIndexRoute = ReadinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadinessRoute,
} as any)
const ReadinessOpsRoute = ReadinessOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => ReadinessRoute,
} as any)
const ReadinessConfigRoute = ReadinessConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ReadinessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charging': typeof ChargingRoute
  '/drivers': typeof DriversRoute
  '/fleet': typeof FleetRoute
  '/intelligence': typeof IntelligenceRoute
  '/mis': typeof MisRoute
  '/readiness': typeof ReadinessRouteWithChildren
  '/routes': typeof RoutesRoute
  '/segments': typeof SegmentsRoute
  '/readiness/config': typeof ReadinessConfigRoute
  '/readiness/ops': typeof ReadinessOpsRoute
  '/readiness/': typeof ReadinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charging': typeof ChargingRoute
  '/drivers': typeof DriversRoute
  '/fleet': typeof FleetRoute
  '/intelligence': typeof IntelligenceRoute
  '/mis': typeof MisRoute
  '/routes': typeof RoutesRoute
  '/segments': typeof SegmentsRoute
  '/readiness/config': typeof ReadinessConfigRoute
  '/readiness/ops': typeof ReadinessOpsRoute
  '/readiness': typeof ReadinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charging': typeof ChargingRoute
  '/drivers': typeof DriversRoute
  '/fleet': typeof FleetRoute
  '/intelligence': typeof IntelligenceRoute
  '/mis': typeof MisRoute
  '/readiness': typeof ReadinessRouteWithChildren
  '/routes': typeof RoutesRoute
  '/segments': typeof SegmentsRoute
  '/readiness/config': typeof ReadinessConfigRoute
  '/readiness/ops': typeof ReadinessOpsRoute
  '/readiness/': typeof ReadinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charging'
    | '/drivers'
    | '/fleet'
    | '/intelligence'
    | '/mis'
    | '/readiness'
    | '/routes'
    | '/segments'
    | '/readiness/config'
    | '/readiness/ops'
    | '/readiness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charging'
    | '/drivers'
    | '/fleet'
    | '/intelligence'
    | '/mis'
    | '/routes'
    | '/segments'
    | '/readiness/config'
    | '/readiness/ops'
    | '/readiness'
  id:
    | '__root__'
    | '/'
    | '/charging'
    | '/drivers'
    | '/fleet'
    | '/intelligence'
    | '/mis'
    | '/readiness'
    | '/routes'
    | '/segments'
    | '/readiness/config'
    | '/readiness/ops'
    | '/readiness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChargingRoute: typeof ChargingRoute
  DriversRoute: typeof DriversRoute
  FleetRoute: typeof FleetRoute
  IntelligenceRoute: typeof IntelligenceRoute
  MisRoute: typeof MisRoute
  ReadinessRoute: typeof ReadinessRouteWithChildren
  RoutesRoute: typeof RoutesRoute
  SegmentsRoute: typeof SegmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis': {
      id: '/mis'
      path: '/mis'
      fullPath: '/mis'
      preLoaderRoute: typeof MisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charging': {
      id: '/charging'
      path: '/charging'
      fullPath: '/charging'
      preLoaderRoute: typeof ChargingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/': {
      id: '/readiness/'
      path: '/'
      fullPath: '/readiness/'
      preLoaderRoute: typeof ReadinessIndexRouteImport
      parentRoute: typeof ReadinessRoute
    }
    '/readiness/ops': {
      id: '/readiness/ops'
      path: '/ops'
      fullPath: '/readiness/ops'
      preLoaderRoute: typeof ReadinessOpsRouteImport
      parentRoute: typeof ReadinessRoute
    }
    '/readiness/config': {
      id: '/readiness/config'
      path: '/config'
      fullPath: '/readiness/config'
      preLoaderRoute: typeof ReadinessConfigRouteImport
      parentRoute: typeof ReadinessRoute
    }
  }
}

interface ReadinessRouteChildren {
  ReadinessConfigRoute: typeof ReadinessConfigRoute
  ReadinessOpsRoute: typeof ReadinessOpsRoute
  ReadinessIndexRoute: typeof ReadinessIndexRoute
}

const ReadinessRouteChildren: ReadinessRouteChildren = {
  ReadinessConfigRoute: ReadinessConfigRoute,
  ReadinessOpsRoute: ReadinessOpsRoute,
  ReadinessIndexRoute: ReadinessIndexRoute,
}

const ReadinessRouteWithChildren = ReadinessRoute._addFileChildren(
  ReadinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChargingRoute: ChargingRoute,
  DriversRoute: DriversRoute,
  FleetRoute: FleetRoute,
  IntelligenceRoute: IntelligenceRoute,
  MisRoute: MisRoute,
  ReadinessRoute: ReadinessRouteWithChildren,
  RoutesRoute: RoutesRoute,
  SegmentsRoute: SegmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
